language: python
sudo: required
python:
    - "2.7"
env:
    - CKAN_VERSION=master
    - CKAN_VERSION=dev-v2.8
services:
    - postgresql
    - redis-server
install:
    - bash bin/travis-build.bash
    - pip install coveralls
script: sh bin/travis-run.sh
after_success:
    - coveralls
cache:
  directories:
    - $HOME/.cache/pip
